# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(max_length=100)),
                ('music', models.CharField(max_length=100)),
                ('books', models.CharField(max_length=100)),
                ('checkins', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=75)),
                ('facebook_id', models.IntegerField(default=0)),
            ],
        ),
    ]
