# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='', max_length=10)),
                ('birthday', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=75)),
                ('state', models.CharField(default='', max_length=75)),
                ('sports', models.CharField(default='', max_length=300)),
                ('music', models.CharField(default='', max_length=300)),
                ('books', models.CharField(default='', max_length=300)),
                ('checkins', models.CharField(default='', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
