# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_facebook_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='users',
            name='facebook_id',
        ),
    ]
