# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170427_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='user',
        ),
    ]
